<!DOCTYPE html>
<html lang="cs-cz">
	<head>
		<base href="/localhost" />
		<meta charset="UTF-8" />
		<title><?= $titulek ?></title>
		<meta name="description" content="<?= $popis ?>" />
		<meta name="keywords" content="<?= $klicova_slova ?>" />
		<link href='https://fonts.googleapis.com/css?family=Roboto:300,400,700' rel='stylesheet' type='text/css'>  
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/> 
    <link rel="stylesheet" href="css/main.css">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	</head>

	<body>
  
		<header>    
      <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>                        
            </button>
            <a class="navbar-brand" href="index.html">Project</a>
          </div>
          <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
              <li class="active"><a href="clanek/uvod">Home</a></li>
      				<li><a href="clanek">Articles</a></li>
      				<li><a href="kontakt">Contact</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
              <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
		
		<br clear="both" />
		
    <section class="container">
  		<article>
  			<?php $this->kontroler->vypisPohled(); // vložení aktuálního pohledu do šablony ?>
  		</article>
		</section>
    
		<footer class="container">    
      <div class="row">      
        <p class="col-sm-4">&copy; 2017 Jakub Červený
        </p>      
        <ul class="col-sm-8">        
          <li class="col-sm-1">                    
            <a href="https://twitter.com/Jalqu1n">          
              <img src="https://s3.amazonaws.com/codecademy-content/projects/make-a-website/lesson-4/twitter.svg">
            </a>      
          </li>        
          <li class="col-sm-1">
            <a href="https://www.facebook.com/cerveny.jakub98">          
              <img src="https://s3.amazonaws.com/codecademy-content/projects/make-a-website/lesson-4/facebook.svg">
            </a>        
          </li>        
          <li class="col-sm-1">          
            <a href="https://www.facebook.com/cerveny.jakub98">          
              <img src="https://s3.amazonaws.com/codecademy-content/projects/make-a-website/lesson-4/instagram.svg">
            </a>         
          </li>          
        </ul>    
      </div>  
    </footer>
    
	</body>
</html>